export default function Head() {
  return (
    <>
      <title>Mit Food Company</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#FFA424" />
    </>
  );
}
